INSERT INTO dbo.Clientes (
    Nombre,
    ApellidoPaterno,
    ApellidoMaterno,
    CorreoElectronico,
    Telefono,
    FechaNacimiento,
    Direccion,
    Ciudad,
    CodigoPostal,
    Activo,
    FechaRegistro
)
VALUES
(
    N'Laura',
    N'Martínez',
    N'Gómez',
    N'laura.martinez@correo.com',
    N'3312345678',
    '1990-05-18',
    N'Av. Vallarta 1500',
    N'Guadalajara',
    N'44110',
    1,
    SYSUTCDATETIME()
),
(
    N'Carlos',
    N'Ramírez',
    N'López',
    N'carlos.ramirez@correo.com',
    N'3398765432',
    '1988-11-03',
    N'Av. Américas 1200',
    N'Zapopan',
    N'45050',
    1,
    SYSUTCDATETIME()
);
GO
